### ISSUE TITLE
RA2 UI

### ISSUE THREAD

**Issue by x-a-n-a-x** [Phrohdoh/oramod-ra2#11]
Here is a first draft for a possible RA2 UI.

![ra2_1](https://cloud.githubusercontent.com/assets/1732773/6500465/5f096bee-c30c-11e4-98ba-b4cfacf4431c.png)

**Comment by Phrohdoh** [comment]
Do you have yaml for this?

**Comment by abcdefg30** [comment]
Looks good to me. :+1:

**Comment by x-a-n-a-x** [comment]
> Phrohdoh said:
> Do you have yaml for this?
No I don't. For the moment, it's just a mock-up image.

**Comment by GraionDilach** [comment]
Looks nice, indeed.

Phrohdoh, you could try a mockup made from http://www.dan-lyons.com/page5.jpg if you don't like release but tbh the shine does fit to RA2's design approaches.

**Comment by Fincer** [comment]
Agreed with the previous comments. It looks nice and loyal to the original style used by Westwood. Keep it up!

**Comment by x-a-n-a-x** [comment]
Small update.
![chrome](https://cloud.githubusercontent.com/assets/1732773/6623419/2f11913c-c8e3-11e4-93e0-c48f9758a80d.png)

**Comment by x-a-n-a-x** [comment]
A small preview of my current progress: 

![screenshot003](https://cloud.githubusercontent.com/assets/1732773/6658491/0c6931d2-cb6b-11e4-84c7-97adce81e5b3.png)

I decided to modify the Production Tabs (Buildings, Support, Infantry, Vehicles, Aircrafts, Ships) because I disliked the original "tabs".

**Comment by Phrohdoh** [comment]
I am wondering (and hoping to spark discussion) if we can make use of the area taken up by the duplicate sawblade portion (right-hand side).

**Comment by x-a-n-a-x** [comment]
You want to get rid of the sawblades ? 
I hoped that once the UI is done, I could try to animate these sawblades (in a SHP file).

**Comment by GraionDilach** [comment]
Looks nice. The alt design had the power bar mirrored there instead of the sawblades, so IMO keep blades - btw will there be working power bar in this or only the numeric output will gonna work?

**Comment by Phrohdoh** [comment]
I think keeping **a** sawblade is fine, but N duplicates is wasteful and unappealing in my opinion.

**Comment by x-a-n-a-x** [comment]
@GraionDilach : I think it would be great if the vertical powerbar worked too. 

It has been requested for the D2K UI, and it's needed for the TD UI (the current TD UI features two vertical bars: power and silo). Unfortunately, this feature (vertical gauge bars) hasn't been implemented yet.

---

@Phrohdoh : the several sawblades look good imo. Having only *one* sawblade (at the top-right or elsewhere) would look weird.. The right side of UI would be empty.

Btw, I hope to be able to create a nice animation (a SHP) for this sawblade, this way, (and with some code), if the player clicks on a icon (on a cameo), the sawblade which is on the same row (on the right) animates.

**Comment by x-a-n-a-x** [comment]
FYI, I have just updated my branch: https://github.com/x-a-n-a-x/OpenRA/tree/new-RA2-UI

For the moment, I have only made the Allies faction UI (and it's still not 100% finished, i'll tweak buttons colors).

**Comment by x-a-n-a-x** [comment]
I have updated the Allies faction UI : https://github.com/x-a-n-a-x/OpenRA/tree/xanRA2UI
It's testable... and shouldn't contain too many bugs.

The Soviets UI art is done but not testable for the moment.
Same for the Observer UI.

**Comment by Phrohdoh** [comment]
Looking good. :smiley:

**Comment by bvandenbogaard** [comment]
Awesome x-a-n-a-x!

**Comment by erkro1** [comment]
Indeed very nice!

**Comment by Snurre86** [comment]
Here are the original, this are not all of them just the once I can build as France.
![desktop_2015_06_13_14_51_56_992](https://cloud.githubusercontent.com/assets/7798635/8144369/146bfd4e-11dc-11e5-9aff-68964cb9fe84.png)
![desktop_2015_06_13_14_52_03_839](https://cloud.githubusercontent.com/assets/7798635/8144371/271d972c-11dc-11e5-8d99-c32cfb9f17fe.png)
![desktop_2015_06_13_14_52_07_968](https://cloud.githubusercontent.com/assets/7798635/8144374/2ebfaf92-11dc-11e5-9593-690dec9a7168.png)
![desktop_2015_06_13_14_52_11_936](https://cloud.githubusercontent.com/assets/7798635/8144375/388657a6-11dc-11e5-8627-704638803fd8.png)
![desktop_2015_06_13_14_52_18_024](https://cloud.githubusercontent.com/assets/7798635/8144376/40a3c7f2-11dc-11e5-9234-220c3a803a3a.png)
![desktop_2015_06_13_14_52_23_135](https://cloud.githubusercontent.com/assets/7798635/8144377/48495a1c-11dc-11e5-95e5-41a26bae9f32.png)

**Comment by Phrohdoh** [comment]
@Snurre86 that is why scrolling was added, so unless there is something else in the images I am missing your point.

**Comment by Snurre86** [comment]
There is no point to make, I am now with you guys on the "3 rows and 5 tabs" as then hopefully scrolling will be eliminated.

**Comment by x-a-n-a-x** [comment]
For the moment, there is no scrolling needed (I am testing the UIs at 1024x768)

**Comment by Snurre86** [comment]
Will the minimap be in aspect ratio 16:9, 16:10 or 4:3?

**Comment by x-a-n-a-x** [comment]
It will be 202x157 pixels, so the same ratio as the original UI

**Comment by x-a-n-a-x** [comment]
I have updated the Soviets faction UI. It's now available but still unfinished.

But now, I currently focus on finishing the Allies side.. and I wonder how to create the buttons. Should they highlight when hovered and pressed? Should only the symbol highlight and the whole button to they move up when pressed? 

You can try these two branches (expect them to be updated from time to time).

https://github.com/x-a-n-a-x/OpenRA/tree/xanRA2UI_highlightedbuttons
https://github.com/x-a-n-a-x/OpenRA/tree/xanRA2UI_pressedbuttons

**Comment by Phrohdoh** [comment]
The new icons are more purple/violet and look plastic to me.
I think the icons ought to be white (or off-white) when hovered.

**Comment by Snurre86** [comment]
Can you make the minimap collapsible to get it out of the way in low tech level missions or personal preference?

**Comment by x-a-n-a-x** [comment]
No, it would require code and I am not a developer (and I don't think these features are supported).

There was an option before (with the old sidebars) to hide the sidebar but players disliked it because during games they - from time to time - accidently hid the sidebar.. which was annoying because they just wanted to build units or buildings..

**Comment by x-a-n-a-x** [comment]
I have resumed my work on this UI and I updated my branch:

**IRC chat:** http://logs.openra.net/?year=2015&month=11&day=28#23:30:13

**screenshots:** https://www.dropbox.com/sh/l8ob6hmktvc6ckq/AADasTcIX0yspPN85zUsj0THa?dl=0

**branch:** (it's an outdated RA2 branch but that you can still try it to test the UI): 
https://github.com/x-a-n-a-x/OpenRA/tree/xanRA2UI_highlightedbuttons

**Comment by Fincer** [comment]
Thanks for updating this. Personally, I like that UI. Looking good! 

There are still two issues, though:

1) I may still raise contrast/brightness of yellow color in Soviet's highlight buttons a little bit. At the current state they seem little blurry/dark. 
2) I may still prefer covering the small gap area between screen edge and the UI. That small gap is visually unaesthetic, I think.

**Comment by GraionDilach** [comment]
The Allied nonhighlighted buttons look bad - the icon blends in too much.

**Comment by MustaphaTR** [comment]
Agrred with @GraionDilach. They look bad.

**Comment by Phrohdoh** [comment]
I see your points they are a bit translucent.
Perhaps a 1 or 2 pt black stroke + making them more opaque would help.

**Comment by x-a-n-a-x** [comment]
New branch: https://github.com/x-a-n-a-x/ra2/tree/RA2_without_powerdown

I created this branch for the maintainers of the RA2 mod, if they consider the powerdown button useless (or at least, not necessary, in case the consensus is to get as closer as possible to a vanilla RA2 mod). 

![ra2ui_without_powerdown_button](https://cloud.githubusercontent.com/assets/1732773/12552156/3f20143a-c370-11e5-9b8d-ab658d37bab2.png)

**Comment by x-a-n-a-x** [comment]
Another branch to play with: https://github.com/x-a-n-a-x/ra2/tree/RA2_without_powerdown_nor_diplomacy

This one doesn't feature the powerdown nor diplomacy buttons.

![ra2ui_without_powerdown_nor_diplomacy_buttons](https://cloud.githubusercontent.com/assets/1732773/12553997/bf4ccd60-c37a-11e5-8c00-68ffbc937cf2.png)

**Comment by abcdefg30** [comment]
Looks like the UI is finished. The pr is at the main repository now: https://github.com/OpenRA/ra2/pull/95
Please comment there if you want to give further input.

**Comment by x-a-n-a-x** [comment]
Almost finished yes. I still plan to redo the Production-tabs (Buildings, Defense, Infantry...) for the soviets faction. And I also want to add the vertical powerbar, if it's possible.

**Comment by x-a-n-a-x** [comment]
Branch for the vertical powerbar: https://github.com/x-a-n-a-x/ra2/tree/RA2_vertical_powerbar
(Note that I need to fix the "indicators")

The vertical powerbar works but there is still one big problem : 
In the TD mod, the power and silo bars have a fixed height while the RA2 mod requires a stretchable vertical powerbar (especially if the production-palette is expanded, which happens if you enable the Build Everything option in Debug).
