### ISSUE TITLE
File not found: C:\Users\Erwin\OpenRA\mods/ra2/uibits/loadscreen.png

### ISSUE THREAD

**Issue by erkro1** [Phrohdoh/oramod-ra2#38]
That's what I get when starting the mod up, I guess it's because of the / and \ being different in thesame file path?

**Comment by Phrohdoh** [comment]
@x-a-n-a-x could you help resolve this?

**Comment by x-a-n-a-x** [comment]
Hi @erkro1.

I had the exact same error. The slashes \ or / have nothing to do with the error. 

When you downloaded the ZIP file (the source code), you probably extracted it to a folder named "oramod-ra2" or else.. Once it has been compiled, I guess you just copied-pasted that folder to "C:\Program Files\OpenRA\mods\oramod-ra2\".

This is exactly why the error occurs. 
You have to rename the mod folder to "ra2" and copy it to ~\OpenRA\mods\

**Comment by erkro1** [comment]
I didn't even copy it to Program Directory, I did it now but still same error :/

**Comment by x-a-n-a-x** [comment]
It doesn't matter if it's in the "program files" folder. 
What matters is how the "ra2" mod folder named.

**Comment by erkro1** [comment]
I know I have named it ra2 like you said

**Comment by abcdefg30** [comment]
Can you post the path you used, please?
(Do you have the mod at `C:\Program Files\OpenRA\mods\`?)

**Comment by erkro1** [comment]
C:\Program Files (x86)\OpenRA\mods\ra2

**Comment by x-a-n-a-x** [comment]
Try **copying** your whole OpenRA folder to C:\
(just to see if spaces in the path "Program Files (x86)" make the error occur).

**Comment by erkro1** [comment]
Still not working

**Comment by x-a-n-a-x** [comment]
have you name it "RA2" or "ra2" ?

**Comment by erkro1** [comment]
lowercase letters, so ra2

**Comment by abcdefg30** [comment]
Does `C:\Program Files (x86)\OpenRA\mods\ra2\uibits\loadscreen.png` exist?

**Comment by erkro1** [comment]
Yeah it does, very weird

**Comment by abcdefg30** [comment]
Um, wait, error is still the same?

**Comment by erkro1** [comment]
Now it is "File not found: audio.mix" actually

**Comment by abcdefg30** [comment]
Ok, then you need to put the ra2 mixes into `C:\Users\Erwin\Documents\OpenRA\Content\ra2`.

**Comment by x-a-n-a-x** [comment]
@erkro1 : if you can, join us on our IRC channel : #openra
http://www.openra.net/community/

**Comment by abcdefg30** [comment]
Solved in IRC.

**Comment by Phrohdoh** [comment]
What was the resolution / steps taken here?
