### ISSUE TITLE
Apocalypse Tank

### ISSUE THREAD

**Issue by Sheepsaurus** [Phrohdoh/oramod-ra2#57]
Crashes the game through various conditions.
If a unit shoots it
If it shoots another unit
If it shoots a building/Defensive building
Does not crash if attacked by a defensive building

**Comment by Phrohdoh** [comment]
#51

**Comment by MustaphaTR** [comment]
It was not crashed at me. I did not target an apocalyse to anyother unit but it was not crashing when it attack to any vehicle, building or infantry.
