### ISSUE TITLE
.gitmodules is missing

### ISSUE THREAD

**Issue by mijofa** [Phrohdoh/oramod-ra2#78]
I'm guessing you've just forgotten to 'git add' the .gitmodules file or something, because both 'clone --recursive ...' and 'submodule init' complain about it not existing:

    $ git clone --recursive https://github.com/Phrohdoh/oramod-ra2.git
    Cloning into 'oramod-ra2'...
    remote: Counting objects: 1319, done.
    remote: Total 1319 (delta 0), reused 0 (delta 0), pack-reused 1319
    Receiving objects: 100% (1319/1319), 2.06 MiB | 536.00 KiB/s, done.
    Resolving deltas: 100% (813/813), done.
    Checking connectivity... done.
    No submodule mapping found in .gitmodules for path 'openra'
    
    $ cd oramod-ra2
    $ git submodule init
    No submodule mapping found in .gitmodules for path 'openra'

**Comment by abcdefg30** [comment]
Is https://github.com/Phrohdoh/oramod-ra2/commit/718f25ff241b3ae8a3af30dba8e7f825616d59e2 what you wanted? (I'm not familiar with submodules.)

**Comment by mijofa** [comment]
Yep, that fixed it, thanks. :)
